# Generated by Django 6.1.1 on 2026-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Framer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Date_Birth', models.DateField()),
                ('id_Number', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
