# Generated by Django 6.1.1 on 2026-09-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Framer', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_Number',
            new_name='Id_number',
        ),
    ]
