# Generated by Django 6.1.1 on 2026-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Framer', '0003_rename_id_number_userprofile_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Date_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
